- code/modules/mob_spawn/mob_spawn.dm
Gives ghostroles the ability to spawn with your character, loadout, and quirks.  This is blocking for Rhaplanca's work, so even though there's a little more work that needs doing (e.g, ashies are going to be scrungly real quick, no code in place for making sure players are the right species for the role), I'm not going to block progress by lumping this into The Prefsening.
:cl:
qol: ghostroles use your character now!
/:cl:
> [NONMODULAR] Ghostroles Get Goods

- .github/workflows/codeowner_reviews.yml
Seems to be a permissions issue, this might fix it.
Checks need to work.
:cl:
/:cl:
> Potential fix for codeowners?

- tools/build/build.js
We forgot to add this very important thing.
Let's stop gambling for good luck.
:cl: MortoSasye (Kaostico Found it)
code: Added modular_doppler to the build.js
/:cl:
> Build.js includes modular_doppler

- .github/CODEOWNERS
Adds honkpocket as a requester reviewer.
> Adjusts CODEOWNERS

- code/modules/mob/living/carbon/examine.dm
~~Fix for the~~ Adds SSD indicator timer on the new examine rework from TG
Don't you like it when things work? I do. (Apparently it didn't exist before, so yeah... new shiny thing!)
:cl: Kaostico
add: SSD timer on examine added
/:cl:
> Adds SSD timer on examine

- code/modules/mob/living/carbon/human/human_update_icons.dm
The requested change from Naaka, so she can test this weird bug on the female uniform.
Trust me, I know what I'm doing
<sub> (I certainly do not know) </sub>
:cl:
fix: fixed female uniform update... apparently
/:cl:
> Supposed fix for the female uniform icon (NAAKA PLEASE SAVE US)

- modular_doppler/modular_cosmetics/code/face/basemasks.dm
This fixes the visual bug of the bandanas.
We are not really big fans of the missing texture aesthetic
:cl: Kaostic
fix: Fixed bandana's visual glitch
/:cl:
> Quick bandana fix

- code/__DEFINES/role_preferences.dm
- code/__DEFINES/~doppler_defines/role_preferences.dm
- tgstation.dme
Something about defines and load orders.
Fixes: https://github.com/DopplerShift13/DopplerShift/issues/96
:cl:
fix: Fixes Space Sapper Opt In Pref
/:cl:
> Fixes Space Sapper Opt In Pref

- .github/CODEOWNERS
added Dawson
Dawson
:cl:
/:cl:
> added new Maptainer to CODEOWNERS

- modular_doppler/languages/language_datums.dm
Fixes the bug where the hearthkin could understand, but not speak, Ættmál.
I have no mouth and I must scream.
fix: Hearthkins can once more speak their native sacred tongue.
/:cl:
> Hearthkin Language Hotfix

- code/modules/surgery/bodyparts/species_parts/misc_bodyparts.dm
- modular_doppler/modular_species/species_types/golem/golem.dm
Adds in the lore for the bestie. Does some adjustment to their unarmed verbs because it didn't work on-server. Cleans up a single misstep.
I love lore bro. Check out https://wiki.dopplershift13.com/wiki/Golems
:cl:
add: Golem lore!!
/:cl:
> Some Light Golem Tweaks

- code/modules/client/preferences_savefile.dm
Fixing the languages menu to work properly- part 1 of such, at least!
- Languages now properly save as part of your character
- Languages save/load correctly per slot
TODO:
- Give Ramatae their beep boop understanding without needing to sacrifice all your lang slots?
Languages menu peam, we need it working.
:cl:
fix: languages save/load per character slot
/:cl:
> [SEMIMODULAR] Languages: The Fixening

- _maps/map_files/Mining/Iceland.dmm
Fixes two missing pipes on second layer mining base, and the missing power cells in the power station of the Ice variant of mining base.
Fix and parity.
:cl:
fix: Missing pipes on z2 Mining Base junction
/:cl:
> Pipes and Cells

- modular_doppler/modular_antagonists/sapper_gang/sapper_event.dm
Just tweaks some of the conditions for this event to run, mostly so the event poll panel doesn't bring up this event all the time.
Variation!
:cl:
code: Properly implements Space Sappers event conditions
/:cl:
> Space Sappers event conditions tweak

- modular_doppler/enterprise_resource_planning/code/breasts.dm
I'm going to blow up.  The accidental chest surgerification on all of the Dopplerheads was a single missing return.
Things actually work.
:cl:
fix: boobs
/:cl:
> [MODULAR] Parts-Display Normie Mode: The Fixening

- code/modules/mob/living/simple_animal/hostile/megafauna/wendigo.dm
- modular_doppler/modular_mobs/simple_animal/megafauna/wendigo.dm
- tgstation.dme
changes the name of the wendigo megafauna to Eikþyrnir by request. to keep the nonmodular edits down i only touched the names and descriptions of player facing things in a modular override file.
MS-18E Kampfer
:cl:
change: the wendigo is Eikþyrnir now
:cl:
> changes the name of the wendigo by request

- _maps/doppler/automapper/templates/birdshot/birdshot_cryo.dmm
Forgot this when porting cryo. Makes player belongings not fall on the floor anymore.
:cl:
fix: Fixes birdshot cryo not having a cryo computer
/:cl:
> Fixes birdshot's cryo computer (from being missing)

- .github/CODEOWNERS
Read the title that said it all.
I'm god and also some names in here dont have repo write access anymore so it throws errors about them.
> Adds me to codeowners for many things and fixes codeowner file errors by removing names that dont have write access to the repo

- code/__DEFINES/~doppler_defines/traits.dm
- code/modules/surgery/bodyparts/_bodyparts.dm
- modular_doppler/modular_quirks/cybernetic_limb_mounts/cybernetic_limb_mounts.dm
- tgstation.dme
Really basic: just brings over the CLM quirk from Nova and lightly adjusts it to work with our androids.
Robots being able to do robot things is generally excellent.
:cl: yooriss
add: The Cybernetic Limb Mounts quirk is now available. It allows you to detach and reattach any robotic limbs (except your head and your chest) at will.
/:cl:
> Port over cybernetic limb mounts quirk

- code/modules/client/preferences.dm
Doubles our character slot count, somehow people have 15 characters already.
More slots innit
:cl:
qol: More Slots
/:cl:
> [Non-Modular] Moooore slots

- modular_doppler/modular_quirks/permitted_cybernetic/permitted_cybernetic.dm
Somebody requested this to be added, and yeah.
If you think food is boring, why have to eat.
:cl:
balance: Adds a Nutriment pump option to permitted implant quirk
/:cl:
> Adds Nutri-Pump MINUS to implant quirk

- modular_doppler/modular_cosmetics/code/under/doppler_uniforms.dm
I pasted the wrong file path into both of them
Janitor :+1:
:cl:
fix: Fixes janitor uniforms being wrong
/:cl:
> fixes janitor uniforms having reversed obj and mob icon files

- code/modules/loadout/categories/neck.dm
- modular_doppler/loadout_categories/categories/neck.dm
It was put in the wrong file
:+1:
> makes #251 modular

- modular_doppler/human_health_maximum/code/to_the_limit.dm
- tgstation.dme
150 from 100, drop me dead
Instances slightly less of the tg superfrag war machine instakilling me while im trying to rp with a revolver in juni's mouth
:cl:
balance: Humans and subtypes have more health now
/:cl:
> Pushes human health to a higher number

- modular_doppler/modular_customization/accessories/code/moth_accessories/moth_wings.dm
- tgstation.dme
tg added a new flavor of moth wings and we overwrote the icon file, but did not have an icon for it
the prefs menu should look correct again
:cl:
fix: fixes missing thing that would get put in the spritesheet
/:cl:
> fixes missing thing from the sprite sheet that was ruining everything

- _maps/RandomRuins/IceRuins/doppler/icemoon_underground_icewalker_lower.dmm
- modular_doppler/hearthkin/primitive_genemod/code/map_items.dm
Removes practically all of the modular version of hotsprings because tg copied it practically 1:1 except it looks cooler.
Icecats can no longer ddos the server by bathing
:cl:
fix: Fixes insane lag caused by icecats bathing
/:cl:
> Significantly Reduces Lag Caused by Icecats Bathing

- code/modules/paperwork/paperwork.dm
adds line saying you can examine the stampable paperwork for cargo further
i would have probably known what to do with this without ahelp if this line was there
:cl:
qol: Messy paperwork sent in to cargo now informs you that you can skim through it for more info.
/:cl:
> Paperwork extended examine

- code/modules/mob/living/basic/pets/parrot/poly.dm
Makes poly speak once every 2.5m instead of once every 5s on avg
stop fucking yapping stupid parrot
:cl:
qol: Makes poly speak significantly less, once every 2.5m on average instead of once every 5s
/:cl:
> Makes the parrot shut the fuck up

- modular_doppler/modular_quirks/bouncy/bouncy.dm
- tgstation.dme
What's on the tin, that's really it.
Bootleg walking animation for characters that it would fit for, like avian type anthros.
:cl:
add: Bouncy quirk that gives you the waddle element
/:cl:
> Quirk that makes you do the waddle animation

- modular_doppler/colony_fabricator/code/appliances/wind_turbine.dm
- modular_doppler/colony_fabricator/code/cargo_packs.dm
- modular_doppler/colony_fabricator/code/design_datums/flatpack_machines.dm
- modular_doppler/colony_fabricator/code/machines/rtg.dm
- modular_doppler/colony_fabricator/code/machines/solid_fuel_generator.dm
- modular_doppler/colony_fabricator/code/machines/stirling_generator.dm
- modular_doppler/damage_control/code/breach_gear.dm
turns out past me before past me was on the money with power generation, actually
what if you wanted to scene but the engine exploded and now you gotta spend the entire round scrounging for power
:cl:
add: adds a new crate to cargo, containing nine wind turbines
balance: makes some sources of power more powerful
/:cl:
> un-nerfs colony power generation, makes the stirling generator actually practical to use in any situation, wind turbines on order

- modular_doppler/underworld_connections/underworld_connections_quirk.dm
the name was set wrong
the prefs actually work now
:cl:
fix: fixes black market smuggler's preferences
/:cl:
> fixes black market smuggler

- code/game/objects/items/storage/boxes/food_boxes.dm
This test seems incredibly stupid but whatever.
> Fix orderable_items unit test failure

- code/game/machinery/dna_infuser/organ_sets/fox_organs.dm
🆑 
fix: fixes fox ears with jank (this shouldn't be / have been fullmerged because it masks an underlying issue)
/🆑
> [TM ONLY] fixes fox ears

- modular_doppler/modular_cosmetics/code/shoes/rollerblades.dm
fixes a single line in the rollerblades dm, clearing a runtime and improving player feedback
fuck bugs 🐛 🔫
> fixes a rollerblade runtime

- modular_doppler/deforest_medical_items/code/treatment_zone_projector.dm
makes them never ever layer on top of people which is really annoying
see about the pull request
:cl:
fix: the big medical hologram will never ever layer on top of people again
/:cl:
> makes the big medical holograms plane under mobs

- modular_doppler/cryosleep/code/cryopod.dm
From https://github.com/NovaSector/NovaSector/pull/4878
:cl:
fix: prison cryo pods work again
/:cl:
> Wallmounted cryopod fix

- code/modules/modular_computers/computers/item/computer.dm
I wanna fuck around and then find out what happens if we make it so you get free wifi anywhere you go.
Might help fix the chat client thing, might be interesting for people in deep space/on the planet to connect with each other through the miracles of IRC.
:cl:
qol: Modular computers are now long ranged by default.
/:cl:
> [TM ONLY FOR THE MOST PART [EXPERIMENTAL]] Makes Computers Long-Ranged By Default

- modular_doppler/underworld_connections/markets/base_black_market.dm
Fuck my stupid chungus life.
Unit tests succeeding would benefit us all methinks.
> Fixes CI Because Of Cyberbrains

- modular_doppler/loadout_categories/categories/pockets.dm
Holy cannoli this thing does 20 force.
Better replacement comes later.
It's not particularly hard to get the switchblade, but it should be harder than 'the loadout.'
:cl:
balance: The loadout switchblade has been replaced with a much weaker knife.
/:cl:
> Replaces Knifey Spooney Equipment (Replacement of The Loadout Switchblade)

- code/game/objects/items/robot/items/hypo.dm
Adds lidocaine to default mediborg hypospray.
Good for the game because it allows us to stop the forced emotes a lil bit easier. Nova/SR had it, figured I could add it here too.
> Adds lidocaine to default mediborg hypospray.

- code/game/objects/structures/bedsheet_bin.dm
There exists a nonmodular change in living.dm here d894a875fdac179dd5696782818e9581f2d40dfb
Where /mob/living/proc/on_lying_down(new_lying_angle) is changed to move some pixel shifting off pixel_y to pixel_z
All that's really above lil ol Pink I do not understand the gravitas or grand design here. "Rendering" is just a word Ephe uses to make me cry.
Anyways that change fucks with the exact alignment of bedsheets onto my blorbo. This solution might be scuffed. But I can finally sleep at night.
:cl:
fix: bedsheets now align vertically correctly
/:cl:
> now now, i know it looks bad (Bedsheet alignment)

- modular_doppler/item_visuals/code/random_rotation.dm
Adds a cute lil verb in the IC tab that allows you to skewn't on drop. Still affects all the other sources of skew like throws. 
We are one step closer to me being able to tuck bitches into bed properly. It technically fixes https://github.com/DopplerShift13/DopplerShift/issues/436
The bedsheet being vertically offset is an entirely unrelated battle I'll have to fight another day to achieve my dream.
:cl:
add: Added a toggle to item rotation on drop
/:cl:
> Adds a toggle verb for item skew on drop

- _maps/map_files/Pubbystation/pubbystation.dmm
- modular_doppler/automapper/code/area_spawn_entries.dm
FAILURE 1: /datum/area_spawn/prison_cryo_console could not find any suitable turfs among nothing. at code/modules/unit_tests/~doppler/automapper.dm:32
FAILURE 2: /datum/area_spawn/prison_cryopod could not find any suitable turfs among nothing. at code/modules/unit_tests/~doppler/automapper.dm:32
Pubby does not have a perma. It places its perma prisoners in a fish bowl that's considered the brig area, which is not an acceptable area for the area spawn test. So I've made it acceptable.
Contributors will be able to sleep at night
:cl:
fix: fixed github screaming at me because Pubby doesn't have a perma
/:cl:
> Defeating Integration Tests (pubbystation)

- code/datums/wounds/slash.dm
- modular_doppler/most_evil_health_rework/code/yo_doc_im_bleedin_here.dm
- tgstation.dme
People have been upset by the rate of bleeding out and bleed wounds for a long time and have spoken their piece. I have heard the voices of the people and made some minor changes to the flow rates of bleeding wounds to be less devastating but still have impact. Just, not bleed out in ten seconds because you looked too hard at a plastic knife.
With our increase in HP numbers and changes to combat, bleed wounds have been far more common and become a thorn in our side. This adjusts them slightly to see if it is in a better spot this way.
:cl:
balance: lowered slash wound bleed rates and the minimum flow of bleed wounds so if natural healing is occurring it doesn't remain a minor bleed and force an epipen/bandage
:cl:
> Bleed Made Less Bad

- modular_doppler/modular_customization/preferences/cyber_limbs.dm
You can now select missing limb in the character pref menu 
As a synth you can even spawn without a head! ( I couldn't test this bc the synths having organs in their head is just TM'd)
It's really weird you can't spawn with any missing limbs for all our body purists who lose limbs or robors who want to be headless.
Compiles and works fine on local
:cl:
add: Missing limb as an option to limb choices in pref screen
/:cl:
> Allows you to spawn with missing limbs

- modular_doppler/modular_weapons/code/weapon_overrides.dm
- tgstation.dme
It's just enabling a singular obj_flag, but honestly I didn't really know where to put it? Let me know if there's a better place to do it, or a better method to do it. i just made a file in our modular_weapons for future quick modular overrides like this.
:cl:
add: Renaming to the HoS Gun
/:cl:
> Allows the HoS Multiphase energy gun to be Renamed/Re-descriptioned

- code/controllers/subsystem/dynamic/dynamic.dm
Sets "Extended" to be our default dynamic rulestate
This time without me being silly
Lets staff micromanage rounds easier
:cl:
/:cl:
> Changes rule state to default to Extended

- modular_doppler/modular_customization/organs/code/breasts.dm
This fixes the breast layer clipping under hands and hair.
This makes it so it's above hands and hair, as some hairstyles have a part between the arms which clip through the breasts.
It's a super duper cosmetic thing that irked me so bad while making a new character.
:cl:
fix: Fixes breast layer.
/:cl:
> [FIX] Adjusts Breast Layer

- code/modules/loadout/categories/pocket.dm
This adds the option to have spawn in game with a lollipop.
It's cute.
:cl:
add: Added lollipop to the loadout. yum!
/:cl:
> Adds lollipop to the loadout <3

- code/game/machinery/hologram.dm
Tin.
More seriously, the following line would runtime:
https://github.com/DopplerShift13/DopplerShift/blob/58ab3dc07a99c1f4197779d0639b51d5764549b0/code/game/machinery/hologram.dm#L557-L558
Because of this earlier line:
https://github.com/DopplerShift13/DopplerShift/blob/58ab3dc07a99c1f4197779d0639b51d5764549b0/code/game/machinery/hologram.dm#L540-L542
Leading to this:
<details>
<summary>Dealer Warning</summary>
</details>
:cl:
fix: [DOPPLER] Fixed holopads creating static immortal homunculi of the caller if used by non-AIs.
/:cl:
> Fixes holopads creating static immortal homunculi of the caller if used by non-AIs

- modular_doppler/loadout_categories/categories/accessories.dm
the accessory that makes you soggy has been re-added to the loadout. please note that needing to be soggy to breathe through quirk or fish trait automatically puts one on characters already. this one is just for any other flavor reason for a character wanting to track water everywhere constantly and piss everyone off
I, personally, and nobody else, wanted to play a character who needs water but doesn't have gills. Theoretically someone else might too but really it's mostly me.
:cl:
add: loadout accessories tab has hydro-vaporizer again. it is still not necessary to take it for water-breathing
/:cl:
> vaporizer back to loadout

- modular_doppler/modular_species/species_types/android/android_parts.dm
Fixes #613 by having the item using put_in_hands just before the proc returns. Plops on floor as usual if hands are full. And most importantly, not in the user's stomach.
I kept eating limbs I couldn't stop
:cl:
fix: android limb reskinning
/:cl:
> So THATS where all those went (Fixes android limb reskinning

- modular_doppler/loadout_categories/categories/neck.dm
Adds a colourable Mantle to the Accessories tab. It's an option in the ClothesVendor so I see no reason not to add it to the loadout.
Looks good
:cl:
/:cl:
> Adds Mantle to Loadout

- modular_doppler/alt_job_titles/alt_job_titles.dm
Adds more alternative job titles.
Draft as I am still considering more and taking feedback.
Variety is the spice of life.
:cl:
add: New alternative job titles
modify: Changed alt job titles to use more neutral pronouns
/:cl:
> Adds more alternative job titles

- modular_doppler/modular_jobs/command_bodyguard/code/command_bodyguard.dm
- modular_doppler/modular_jobs/command_bodyguard/code/devices/choice_beacon.dm
- tgstation.dme
Gives the Command Bodyguard a choice beacon with a few clothing options, I intend to expand this list once we get more things tailored for security, but for the time being gives a few basic options.
Gives some options for Bodyguard players as well as reducing the need for them to scavenge security for basic supplies.
:cl:
add: choice beacon for command bodyguard
/:cl:
> Adds choice beacon to Command Bodyguard

- modular_doppler/modular_crafting/code/crafting_melee.dm
- tgstation.dme
This cool sword from upstream finally made it here, and I had been planning to make a crafting recipe for it once it did! So I asked 
necromanceranne what the crafting recipe of the sword would be like.
Cool sword with great combat mechanics, as well as being a bit more sci-fi than forge weapons.
:cl:
balance: Adds a crafting recipe for the surplus energy sword! Its no longer Black Market only.
/:cl:
> Crafting recipe for the surplus e sword 

- modular_doppler/modular_quirks/limping/limping.dm
Single line change where I fucked up and accidentally put `affected_side` instead of `severity_choice_list` when shifting around some code, causing it to runtime in the case of a random severity and break tests- except by a stroke of pure luck it never happened when running tests on the quirk pr itself.
Swapping these out fixes it.
No more flaky tests.
Look at the quirk validity tests chief- and running it ingame doesn't runtime.
:cl:
fix: Limping quirk random severity works properly.
/:cl:
> Fixes a random severity for the limping quirk runtiming.
