DopplerShift13/DopplerShift

code/game/atom/_atom.dm
code/game/atoms_movable.dm
code/modules/mob/living/living_defense.dm
modular_doppler/face_mouse_preferences/code/face_mouse_pref.dm
tgstation.dme
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/face_mouse_combat.tsx

When the preference is enabled (true by default) your character will face the mouse while you are in combat mode
It probably isn't that much good but it's cool and I can spin really fast with it
:cl:
add: Adds a preference (true by default) for facing your cursor in combat mode
/:cl:

Adds a preference for facing your mouse while in combat mode

---

code/__DEFINES/subsystems.dm
modular_doppler/administration/code/whitelisting.dm
modular_doppler/administration/readme.md
tgstation.dme

Adds the administration module which currently has the automatic whitelist refreshing subsystem requested by Kannthus.
Because automatization is good.
:cl: Kaostico
add: Add automatic whitelist refreshing subsystem.
/:cl:

Add automatic whitelist refreshing subsystem

---

_maps/RandomRuins/IceRuins/doppler/icemoon_underground_icewalker_upper.dmm
modular_doppler/hearthkin/primitive_production/code/ceramics.dm
modular_doppler/hearthkin/tribal_extended/code/crafting.dm

Placed some larger bottles in the hearthkin's hearth.
Also fixed the issue of wooden and ceramic bowls icons vanishing after their contents get emptied.
I hate bugs + larger bottles are more useful for hearthkin than the lack of them.
add: Swapped the smaller bottles with it's larger cousin, in the hearthkin's healing hut.
fix: Wood bowls and ceramic bowls will no longer magically vanish upon getting it's contents emptied.
/:cl:

Fix: Bowls no longer vanish & larger bottles

---

code/game/objects/items/stacks/golem_food/golem_status_effects.dm
code/modules/mob/living/carbon/human/species_types/snail.dm
modular_doppler/modular_species/species_types/golem/golem.dm
modular_doppler/modular_species/species_types/snails/snail_bodyparts.dm

Snails now get actually sped up when they crawl; roughly equivalent to human crawl speed. Golems are a little faster than before, still mad slow with plasteel, plasteel now gives them a little bit more because I forgot to take into account that they can't otherwise wear armor.
I like walking at a decent pace.
:cl:
balance: Snails and golems walk faster, plasteel does a little more for golems.
/:cl:

Some Shit That I Forgot (Golems & Snails)

---

modular_doppler/modular_mob_spawn/code/mob_spawn.dm

Fixed restricted species not validating correctly when the restricted_species list is empty.
It's broken and we need to fix it.
:cl: Kaostico
fix: Fixed validation from restricted species in ghost roles.
/:cl:

Fixes mob spawn restricted species validations

---

code/modules/client/preferences.dm
tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferenceWindow.tsx

Changed character preferences screen to have a droplist instead of buttons to choose character.
Changed preferences.dm to have a maximum of 15 character slots and 30 if Byond member.
Moar slots!
:cl: Kaostico
add: Swapped buttons for a nice looking dropdown list for character selection in the Character Preference window
add: Max character slots is now 15 and 30 for Byond members. Go nuts! 
/:cl:

[NON-MODULAR] More characters slots and droplist instead of buttons

---

code/modules/mob/living/carbon/examine.dm

Totally a nitpick PR.
Grammar.

Species name in examine is lowercase

---

_maps/doppler/automapper/automapper_config.toml
_maps/mining_configs/iceland.json
code/datums/ruins/icemoon.dm
config/iceruinblacklist.txt

1. Changed the hearthkin's location in Iceland to be in the middle instead.
2. To avoid an efficiency issue with the Icemoon Lavaland Drake boss arena, it was moved from being underground to surface level, and edited. (The efficiency issue was 400+ active turfs in multiple levels, INCLUDING the station)
The 400+ active turfs live in my nightmares.
qol: The hearthkin's base on Iceland is no longer directly above a plasma river, nor in direct proximity to the mining base.
fix: Moved the Ice-Ruin Lavaland Incursion (drake boss arena) to the surface level, to avoid over 400 active turfs in lower levels.
/:cl:

Evil Iceland Ruins Mini-Fix

---

modular_doppler/languages/language_datums.dm

Fixes language icons. When a nonexistent icon_state is inserted into a spritesheet it dumps the entire icon contents into it, which throws everything off. `movepeak` did not exist.
TG needs a test upstream to catch this.

Fixes language icons

---

modular_doppler/research/designs/limbgrower_designs.dm
tgstation.dme

adds all this shit
and also species limbs! except golems because they have those already.
:cl:
adds: Some more options for the limb grower.
/:cl:

Limb Grower Additions

---

code/__DEFINES/~doppler_defines/preferences.dm
code/modules/client/preferences.dm
code/modules/mob/dead/new_player/preferences_setup.dm
modular_doppler/modular_customization/preferences/preferences.dm
modular_doppler/modular_customization/preferences/preferences_setup.dm
tgstation.dme
tgui/packages/tgui/interfaces/PreferencesMenu/MainPage.tsx
tgui/packages/tgui/interfaces/PreferencesMenu/data.ts

it displays your johnson i think.
the window's too big and the choices won't update, send help.
checking things compulsively
:cl:
add: Adds clothing preferences for the preview window.
/:cl:

[help wanted!] job/loadout/underwear/nakey pref.

---

code/__DEFINES/~doppler_defines/is_helpers.dm
modular_doppler/modular_species/species_types/genemod/genemod.dm
modular_doppler/modular_species/species_types/hemophage/hemophage_species.dm
modular_doppler/modular_species/species_types/snails/modular_snail.dm

Genemodders, hemophages, and snails can now have weird fucked up evil legs. These will ideally be better with markings when we get them.
Further customization and one more item off the list, baybee.
:cl:
add: Hemophages, genemodders, and snails can now select digitigrade legs.
/:cl:

Adds Digilegs To Three Species

---

code/modules/reagents/chemistry/reagents/drinks/drink_reagents.dm
code/modules/reagents/chemistry/reagents/food_reagents.dm

Currently, overdosing on char or Monkey Energy makes you randomly say wonderful lines such as these:
This is not particularly conductive to good rp, so this PR disables that.
It's better when your character doesn't randomly start saying meme lines after eating a steak that has been grilled for too long. 
:cl:
del: Removed overdose effects for char and Monkey Energy
/:cl:

Disables the char and Monkey Energy overdose effects.

---

code/modules/loadout/loadout_items.dm
modular_doppler/loadout_categories/categories/clothing.dm
modular_doppler/loadout_categories/loadout_checkers.dm

This one properly turns on letting you rename and redescribe loadout items.
Also ports big shirts for comfy girls.
I NEED to rename everything that I have on my golem for aesthetics.
:cl:
add: You can now rename and redescribe loadout items.
add: Big shirts are in the loadout now.
/:cl:

Renameable Loadout Items (& Some More Ones)

---

modular_doppler/modular_medical/reagents/synth_blood.dm
tgstation.dme

This is my first PR! woo! I'm going to assume there will be workshopping of this, but here goes:
(Should) Adds two new reagents, Hydrofluoric Acid and Synthetic Thermal Solution. Synthetic Thermal Solution is NOT implemented as an exotic blood type at this time pending a full synth species being chosen/created/ported. Synthetic Thermal Solution has the appearance of very pale blue liquid. I added recipes for both the acid and the solution, so they should be able to be created by chemistry in round. 
Hydrofluoric Acid is a necessary ingredient reagent to synthetic thermal solution.
Hydrofluoric Acid is slightly more damaging than nitric acid, but is the same toxicity.
Unique blood for robots! Establishes a reagent with room to grow beyond its roots, unlike oil - which needs to remain oil …

The blood dimension opens

---

modular_doppler/modular_medical/reagents/bug_blood.dm
tgstation.dme

Adds three reagents and their associated recipes
true blood for insects! plus some precursor chemical compounds that can be used for future recipes.
:cl:
add - Hemolymph, a newreagent to serve as the exotic blood type for the insectoid and snail species. (and any other invertebrates we might have in the future)
add - Imidazole, an organic compound, used in the recipe for Hemolymph.
add - Glyoxal, an organic compound, used in the recipe for Imidazole.
add - recipes for the above.
/:cl:

Buggy blood (but functional)

---

code/modules/client/preferences/names.dm

I couldn't figure out how to make it a halfway point so I'm sinking my nuts in the sulfuric acid because I like you.
Especially you.
This allows you to finally have a name like, say, Ăstrid de'Pűssėaeater, or Δ-477 for robots.
If you do dumb shit with this it's a QC issue. I mean it. I will destroy you. Do not show up a fuggin john brown lowercase.
Especially you.
Robots and clones and weirdos.
:cl:
add: Names now use permissive sanitizing.
/:cl:

Trusting You With Something Because I Love You (Permissive Name Formatting)

---

modular_doppler/height_scaling/code/icons.dm
modular_doppler/height_scaling/code/preferences.dm
modular_doppler/height_scaling/readme.md
tgstation.dme
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/dopplershift_preferences/height_scaling.tsx

Adds medium, short, and tall body heights. Works with all species (my husband made me check!!)
Original code is by nikothedude.
<details>
</details>
This is the lesser evil vs porting sprite scaling which ruins sprites. In this essay I will explain why-
:cl: 
add: Added height scaling. You can now be short, standard height, or tall.
/:cl:

Adds height scaling

---

modular_doppler/loadout_categories/categories/belts.dm
modular_doppler/loadout_categories/categories/clothing.dm
modular_doppler/loadout_categories/categories/gloves.dm
modular_doppler/loadout_categories/categories/heads.dm
modular_doppler/loadout_categories/categories/neck.dm
modular_doppler/loadout_categories/categories/pockets.dm

Adds in some entries for some of the GAGS items that Kittysmooch made.
Drip!
:cl:
add: The ranger poncho, various capes, the face scarf, and the maid outfit is in the loadout now.
/:cl:

why do they call it a load out when you load in the

---

code/__DEFINES/~doppler_defines/signals.dm
code/datums/components/jousting.dm
code/game/objects/items/melee/baton.dm
modular_doppler/modular_weapons/code/jousting.dm
modular_doppler/modular_weapons/code/melee.dm
tgstation.dme

Bringing them up to Nova par. You can joust with them too.
Zappy.
:cl:
balance: Batongs are no longer a two-hit stamcrit.
/:cl:

Baton Rebalancing

---

modular_doppler/modular_cosmetics/code/jacket_pockets.dm

jacket pockets were overriding alt click zips on jackets and such, this is a single line fix that ensures the alt click will transform jackets. pockets can still be accessed simply by clicking on the jacket, with sprite dragging being used to remove the jacket.
its a bug fix

fixes pockets overriding jacket transforms

---

modular_doppler/languages/code/language_datums.dm
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/age.tsx
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/dopplershift_preferences/lore.tsx

Fixed gutter (Plutonian) not being able to be spoken.
Also changed the age descriptions since they were interchanged, with the proposal by Iska.
<details>
</details>
I HATE BUGS
fix: Fixed Age and Age Chronological descriptions being incorrect. Also defined more what each age means.
fix: Plutonian is a tongue that can be spoken once more.
/:cl:

Fix Batch | Plutonian & Age Descriptions

---

modular_doppler/modular_species/species_types/android/android_parts.dm

Oops!
:cl:
fix: Fixes synth monitor emissives overlaying over hair
/:cl:

[NO GBP] (we have no gbp) Fixes synth monitor emissives overlaying over hair

---

modular_doppler/reagent_forging/code/forge_clothing.dm

Fixes https://github.com/DopplerShift13/DopplerShift/issues/158 by pointing to the correct file for worn iron boots.
I Hate Bu-
fix: Forged boots will show their correct icon once more.
/:cl:

Fix | Iron Boots Sprite

---

code/controllers/subsystem/dynamic/dynamic_rulesets_midround.dm
modular_doppler/modular_antagonists/_dynamic_rulesets.dm
tgstation.dme

https://github.com/user-attachments/assets/93681233-70c0-488b-883f-87db7a3a2135
Like Nova, except it gets merged this time.
:cl:
qol: Midround antag and obsessed will now poll if you want the roll, instead of forcing itself upon you
/:cl:

Midround polling for antag and obsessed

---

code/modules/client/preferences_savefile.dm

hi yeah i was reading the repo and testing master while waiting for the application and this was getting in the way so-
Anyhow, it seems the occupation and language menus were breaking due to languages runtiming at this line:
https://github.com/DopplerShift13/DopplerShift/blob/c4f78bcac0ef990a240bff1f38fbb62fba9d4c98/modular_doppler/languages/code/language%20menu/client_languages.dm#L68
Which was due to `preferences.all_quirks` being `null` even though it should never be, which I traced back to us using `save_data["languages"]` where `save_data` could be `null` causing `load_character(...)` to runtime.
Setting it to `save_data?["languages"]` parallel to all the other `save_data` calls there seems to fix it just fine!
yep that's a languages menu 👍 
Fixes runtimes.
:cl:
fix: Fixed language, …

Fixes a runtime issue involving character loading and languages.

---

code/modules/vending/boozeomat.dm
modular_doppler/modular_vending/code/tg_vendors/boozeomat.dm
modular_doppler/modular_vending/code/tg_vendors/cola.dm
tgstation.dme

Robots like to get drunk.
:cl:
add: Synthanol, welding fizz and lubricola is available in the booze-o-mat
add: The booze-o-mat glassware tab is improved
/:cl:

Adds the 'Synth-drink' tab to the booze-o-mat and improves the glassware tab

---

_maps/shuttles/~doppler_shuttles/pirate_sapper.dmm
code/game/objects/items/devices/powersink.dm
modular_doppler/colony_fabricator/code/colony_fabricator.dm
modular_doppler/modular_antagonists/sapper_gang/sapper_outfits.dm
modular_doppler/modular_antagonists/sapper_gang/sapper_shuttle_equipment.dm

Still trying to make this playable :)
The sapper can sap properly, also the turrets don't friendly fire anymore lol.
:cl:
balance: Balances the powersink and creditminer to release more internal heat per tick (so they explode less likely)
fix: fixed the rapid construction fabricator's missing sprite when busy
fix: fixed the Space Sapper's turrets friendly firing
qol: Moves some of the Space Sapper's tools around
balance: Gives the Space Sappers hypernob crystals, just enough for both their uniforms.
balance: The Space Sapper Shuttle now has energy fields at their ports, but is no longer stocked with ATMOS fans
/:cl:

Space Sappers credit miner balancing & fixes

---

code/__DEFINES/living.dm
code/datums/bodypart_overlays/emote_bodypart_overlay.dm
code/datums/components/face_decal.dm
code/datums/diseases/advance/symptoms/shedding.dm
code/datums/quirks/negative_quirks/all_nighter.dm
code/datums/status_effects/buffs.dm
code/game/objects/items/stacks/golem_food/golem_status_effects.dm
code/game/objects/structures/mirror.dm
code/modules/mob/living/brain/brain_item.dm
code/modules/mob/living/carbon/alien/alien_update_icons.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/carbon_defines.dm
code/modules/mob/living/carbon/human/_species.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/reagents/chemistry/reagents/medicine_reagents.dm
code/modules/reagents/chemistry/reagents/other_reagents.dm
code/modules/surgery/advanced/wingreconstruction.dm
code/modules/surgery/bodyparts/_bodyparts.dm
code/modules/surgery/bodyparts/dismemberment.dm
code/modules/surgery/organs/external/_visual_organs.dm
code/modules/surgery/organs/organ_movement.dm

Early mirror of [tgstation:87215](https://github.com/tgstation/tgstation/pull/87215)
Because full parity is still being worked on in https://github.com/DopplerShift13/DopplerShift/pull/146, we have to keep up with some important PRs manually.

Early mirror of tgstation:87215

---

modular_doppler/_HELPERS/preferences.dm
modular_doppler/dopplerboop/dopplerboops.dm
modular_doppler/modular_customization/preferences/dopplerboop.dm
modular_doppler/modular_customization/preferences/middleware/dopplerboops.dm
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/dopplershift_preferences/dopplerboop.tsx

Adds a volume slider under sound options for people that want them to be quieter. Also adds a 'mute' option to the voices for people that want to make no sound.
User requested features !!
:cl:
add: mute dopplerboop voice
add: dopplerboop volume slider
/:cl:

Dopplerboop update: Adds mute option and volume

---

_maps/mining_configs/iceland.json
code/datums/weather/weather_types/radiation_storm.dm

Protects ruins and explicitly Hearthkin ruins from radstorms.  Also minorly nerfs radstorms by removing their ability to scramble your features.  I don't care how fucking radioactive they are, your whole-ass snout isn't going to fall off after five seconds of exposure.  That was a stupid feature.  Also sets the top level of Iceland to have the Mining Z-Trait.  I don't know how I missed that on the first pass, but it's important.
Let's not give the poor cats cancer, yeah?
:cl:
del: feature mutations from radstorms, your snout won't fall off anymore
qol: hearthkin & ruins writ large are now protected from radstorms
/:cl:

[NONMODULAR] RadiationLand-B-Gone

---

code/controllers/configuration/entries/game_options.dm
config/game_options.txt

Port of tgstation/tgstation#87380 with an edit marker until such time as someone up there can actually be asked to re-review it and fix things.  This only effects test instances and servers without a static config, same as upstream.
I'm going to explode if human authority continues to be enforced.  Space racism is fucking cringe.
:cl:
del: human authority is no longer default for nonstatic configs
/:cl:

[NONMODULAR] Human Authority Defaults Consistency

---

code/modules/reagents/withdrawal/generic_addictions.dm

Host request. Just comments out the jitters and coughing from nicotine withdrawal stages. Everything else remains unchanged.
Here's me curing an addiction without a single cough or shake 
It kinda sucks for RP to have ppl coughing and jittering around because they smoke for RP purposes and are stuck in a scene where they cant smoke for 3 minutes.
:cl:Motho
del: Nicotine addictions no longer make you cough and jitter.
/:cl:

[NON-MODULAR] Makes nicotine addictions less annoying

---

code/__HELPERS/announcements.dm
code/__HELPERS/priority_announce.dm
code/controllers/subsystem/ambience.dm
code/controllers/subsystem/vote.dm
code/game/objects/items/devices/radio/radio.dm
code/game/sound.dm
code/modules/client/client_procs.dm
code/modules/client/preferences/migrations/legacy_sound_toggles_migration.dm
code/modules/client/preferences/migrations/sound_checkboxes_migration.dm
code/modules/client/preferences/sounds.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/living/silicon/ai/ai_say.dm
tgstation.dme
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/sounds.tsx

So i made a recent PR that changes some of the announcer sounds. Its a lil too loud 4 some people. Rather than going back, tweaking the sounds, and then sending them for review again, I figure I'll just port this closed PR from TG that allows ppl to set a preference for the volumes of certain sounds. This is that PR. Most of the code is courtesy of sadboysuss's PR: https://github.com/tgstation/tgstation/pull/86932 but I debugged certain parts of it and also added a preference for announcement sounds which is what I wanted in the first place. I also removed the TTS volume part because we dont have that.
Idk how hacky this is and it's certainly not modular so I'd appreciate someone with better knowledge taking a look at it.
Earz :3
:cl:Motho
qol: You can now adjust the volume of certain …

[NON-MODULAR] Volume mixer

---

modular_doppler/languages/code/language menu/client_languages.dm

The code was checking for `TRAIT_LINGUIST` in `preferences.all_quirks`, while that is a list based on quirk _names_.
Replacing this with `/datum/quirk/linguist::name` fixes this.
Fixes jank.
:cl:
fix: The Linguist quirk actually grants an extra language point.
/:cl:

Fixes linguist quirk not granting a fourth language point

---

_maps/doppler/automapper/automapper_config.toml
_maps/doppler/automapper/templates/nebulastation/nebulastation_cryo.dmm

Title. 
crayonpod goode?
:cl:
map: The Port Authority Engineering Guild has installed a cryogenics area into Nebula model stations. It is directly north of arrivals.
/:cl:

Adds a cryopod area to Nebula Station

---

_maps/map_files/Mining/Iceland.dmm

My first mapping project! Reskins the entire mining base currently in-use (iceland) to use Akhter Company Frontier Equipment assets. All walls, windows, most airlocks, and floor tiles have been replaced with their pre-fab variants. The canteen has been expanded into a proper kitchen using the flat-packed kitchen items. 
No, this is not modular. I don't know how to do that.
We have a great amount of pre-fab assets under the Akhter umbrella that are criminally under-integrated into our maps.
This is lore-compliant since the Port Authority would be a professional handler and distributor of colonization supplies, collaborating with other companies.
The Mining base is also a pretty low-traffic area so hopefully this helps change that a bit, by making the base more desirable/unique.
Gulag …

Akhter Company Frontier Equipment Sponsorship

---

code/game/objects/items/devices/scanners/gas_analyzer.dm
code/game/objects/items/devices/scanners/health_analyzer.dm
code/game/objects/items/devices/scanners/slime_scanner.dm

This PR allows blind people the use of gas, health, and slime scanners. It also puts the white canes in the loadout.
This is the 'how the fuck' section.
Alright, so.
There's two easy surface-level possible methods in which these devices could easily work.
Method one simply being https://youtu.be/pQO4S1t2uiA, well, screen readers. This is a technology we have in 2024 our current year that can easily read text back to blind people at EXTREMELY quick speeds, this video's one of the slowest screen readers I've seen. With the addition of alt text (the text you get when you mouse over images on accessibility-friendly website) it'd be rather easy to navigate the UIs we're presented.
Method two would simply be refreshable braille displays. 
These traditionally use a system of round-tipped pins …

Makes Health Analyzers Work 4 The Blind

---

_maps/map_files/Mining/Iceland.dmm

Names all the doors! Finally, you can read what the door means to lead you to. Imagine. Readability.
Separates the Gulag and Security Post into their own - horrible - powernet.
Adds some (Horrible) RTGs to power this new much smaller power net.
Keeping the lights on at the mining base for at least 45 minutes to an hour without player intervention is Good.
:cl:
Removed The wall-mounted space heaters. A few have been placed in maints to compensate.
Added a new powernet for the gulag. Not that we use it, but the SMES unit was draining 50 KWs from the Actually-In-Use portion of the mining base.
/:cl:

Polishes up the Mining Base

---

code/modules/loadout/categories/neck.dm

This adds the recolorable bowtie to the loadout, as the regular necktie cannot be converted into one despite having the icon state.
More options good. 😼
:cl:
add: Added a recolorable bowtie to loadout.
:cl:

Bowtie 4 Loadout

---

modular_doppler/modular_quirks/narcolepsy/narcolepsy.dm
tgstation.dme

Port of the original version of my narcolepsy quirk, it has its own mix of reagents which make pills that function like stimulants but also deal minor toxin damage.
Zzz.
:cl:
add: Narcolepsy can be a selectable quirk now
/:cl:

Port of Narcolepsy quirk

---

code/modules/religion/honorbound/honorbound_trauma.dm

Sec are now just good by default, you can declare them evil manually.
There's going to be many cases in which you'll probably have an honorbound guy's TTRPG party running into conflict with Security, and it'd make sense if you could declare them evil manually.
:cl:
add: Honorbound Chaplains can now find it in them to betray the town guard.
/:cl:

An Extremely Small Tweak To Honorbound

---

code/modules/religion/honorbound/honorbound_trauma.dm

Honorbound mfs can now declare evil.
Actual proof I tested this.
:cl:
fix: Honorbound mfs can now declare evil.
/:cl:

Bugfix To My Last PR Because I Wasn't Paying Attention

---

code/modules/bitrunning/server/obj_generation.dm
modular_doppler/bitrunning_prefs_disks/code/disks/prefs_disk.dm
modular_doppler/bitrunning_prefs_disks/code/outfit_overrides/bitrunner_outfit_override.dm
modular_doppler/bitrunning_prefs_disks/readme.md
tgstation.dme

Implements a new disk that allows bitrunners to select an avatar from their character list to use instead, including all preferences including quirks and optionally loadouts.
This performs evil mock client hacks to allow quirks to be configured, and to have preferences without keeping a reference to the client.
Cool bitrunner avatars 👍 
:cl:
add: [DOPPLER] Bitrunners now spawn with a disk that allows them to select an avatar from their full character list. Taking this into a netpod applies the full character including quirks and optionally loadouts.
add: [DOPPLER] Bitrunners may now buy additional copies of the disk that allows them to select an avatar for 1000 points each.
/:cl:

Implements Bitrunner Prefs Disks (Feat. Quirks & Evil Hacks) (without the blowing up part)

---

modular_doppler/modular_quirks/entombed/code/entombed.dm

Just for aesthetics. Designed mostly so I can pair it with https://github.com/tgstation/tgstation/pull/88369 for plasmaman characters.
It uh. It looks really cool. It doesn't have the yellow visor normally so you probably won't get fooled into thinking it's an actual nukie.
:cl:
image: You can have the Elite MODsuit as a cosmetic-only skin for Entombed.
/:cl:

Adds The Elite MODsuit To Entombed

---

modular_doppler/modsuit_pda_app/tap_to_control.dm
tgstation.dme

You can right click scan people with the modsuit control app open, which will ask the wearer if they accept you linking their pda to your suit. Has a warning that you are handing over total control of your space suit to someone's pda, to be fair. Also has a 5 sec delay before it asks you, so people can't be annoying by spamming you with it.
What if you wanted 2 scene but entombed means you can't take your suit off to link to the pda app
:cl:
add: The modsuit control pda app can be linked to other people's suit on their body with consent
/:cl:

lets the modsuit pda app be linked to worn modsuits (with consent) (for entombed users) (fetishcoding)

---

modular_doppler/deforest_medical_items/code/healing_stack_items.dm
modular_doppler/deforest_medical_items/code/storage_items.dm
modular_doppler/deforest_medical_items/code/vulnerable_status_effect.dm
modular_doppler/epic_loot/code/random_spawners_real.dm

some doppler medical stack items couldnt be used because their try_heal proc was messed up
medical items actually working may be important!
:cl:
fix: doppler medical stack items are now actually functional
/:cl:

fixes some medical stack items

---

modular_doppler/emotes/code/added_emotes/robot_sounds.dm

I added an emote to added_emotes/robot_sounds.dm
The sound file was pulled from the main TG sounds/machines/beep folder and not the modular_doppler since it's already in the game and I don't really understand why there are duplicates to begin with? (this is the case with twobeep.ogg)
This alternative beeping emote was one of my favorite features on Nova, it is a critical part of android heavy roleplay and its absence was the first thing I noted when playing.
The original beep is a harsh, slower and kinda grating sound, suitable cyborgs and when you want to beep _roughly_ at someone. It's chock-full of Kiki. 
Beep2 is far more bouba on the other hand; despite being higher pitch, it is quicker, softer, more rounded sound. A gentle beep.
:cl:
qol: Androids and Cyborgs now have an extra beep, …

Grants beep2 to Androids and Cyborgs

---

modular_doppler/modular_quirks/permitted_cybernetic/permitted_cybernetic.dm

It say it in the title.
Something for engineers to pick that isn't a toolarm. Useful for security too, or anyone looking to mess with them.
:cl:
add: Adds the choice to select welding shield eyes as part of the permitted cybernetics quirk
/:cl:

Welding shield eyes added to cybernetic quirk list

---

modular_doppler/modular_customization/markings/markings_preferences.dm

makes markings not emissive blocking, which was adding a duplicate overlay for every marking applied to your character.
seeing as 99% of every pixel on every marking conforms to your body shape, there will be no noticeable effect to this.
applying overlays when we really dont need to is causing us a lot of problems right now
:cl:
fix: makes body markings stop adding more overlays than they really need to
/:cl:

halves the number of overlays doppler markings give you, making it harder to reach the overlays limit with them

---

modular_doppler/starter_resources/ore_vent.dm
tgstation.dme

the starting ore vent will have a little bit of every resource, though it comes from small boulders so it will still be much faster to just go mining yourself
100 years mining coal mines just so people can play the game on lowpop
:cl:
add: the starter ore vent has a little bit of everything, favoring iron and glass, now
/:cl:

makes the starter ore vent have a little bit of everything

---

modular_doppler/spacer_swimming/spacer_swim.dm

This doesn't actually do anything (since the movement fails) but it does stop a do_after from starting if you try to space-swim into something like a wall as a spacer.

Don't attempt to spaceswim through dense turfs

---

code/__DEFINES/~doppler_defines/traits.dm
code/modules/loadout/loadout_items.dm
code/modules/mob/living/carbon/examine.dm
modular_doppler/loadout_item_examine/examine.dm
modular_doppler/loadout_item_examine/examine_when_worn.dm
tgstation.dme

Really simple: ports https://github.com/Bubberstation/Bubberstation/pull/2349 in all of its glory, allowing people who examine you to click on any loadout items that you've written custom descriptions for. No link appears if you haven't written a description.
Being able to look at people's cool shit is fun!
:cl: yooriss, Majkl-J
add: Ported custom-described loadout item examining from Bubberstation. Original feature courtesy of Majkl-J.
/:cl:

Port renamed loadout items having clickable examine links

---

modular_doppler/accent_toggle/code/accent_toggle.dm
tgstation.dme

Really simple: adds a "Toggle Speech Accent" verb to the IC tab that lets you turn on/off any speech replacements that your tongue organ forces you to have, like lizard's ssssss, fly tongue's zzzing, etc.
This does **not** change your say_mod (says, intones, hisses, etc). That'll come later.
:cl: yooriss
add: You can now toggle your character's coded speech accent via the "Toggle Speech Accent" verb in the IC tab. No more sssssspam (unless you want it, of course).
/:cl:

Add the ability to toggle speech accents

---

code/game/objects/items/storage/backpack.dm

Basic duffelbag code resets the bag back to its hardcoded description when you toggle the zipper; this halts that if the bag has been given a custom name or description.
I think this should work fine. It's functionally a single line change. However, adding a check to an often-called proc on a somewhat common object type fills me with dread. If this should be shuffled around slightly for optimization please let me know.
awesome bag
:cl:
fix: Duffelbags with custom descriptions no longer have them overwritten when unzipped.
/:cl:

Loadout duffelbags no longer lose custom description when unzipped

---

modular_doppler/modular_species/species_types/slimes/code/roundstartslimes.dm

Instead of counting the specific stacks for no reason, we now just check if they're wet. Also makes them stay wet for longer.
This didn't work, and wasn't as much of a weakness as I intended.
:cl:
balance: Slimes now get wetter for longer, and it actually damages them.
/:cl:

Slight Slime Nerfs To Make Them Actually Work As Intended

---

modular_doppler/modular_quirks/undersized/held_undersized_examine.dm
modular_doppler/modular_quirks/undersized/held_undersized_id.dm
tgstation.dme

This pr just adds overrides for a list of procs to the mob holder item, forwarding them to the held person's respective procs if it's a carbon so they let you do funny stuff with undersized people.
Being able to examine held undersized people and actually get their examine text is helpful, at least definitely better than the absolutely nothingburger "this is a tiny clothing item :+1:" text you get normally
Holding your pocket Medical Doctor inhand swiping them to open doors is funny
Picking up your nearest tiny coworker to pay for your lunch on a vendor is funny
:cl:
add: [DOPPLER] Examining undersized people inhand shows you the proper examine for them rather than the holder item examine.
add: [DOPPLER] Undersized people inhand count as whatever ID they're wearing for all intents and …

Undersized Examine and ID code

---

code/modules/research/techweb/nodes/cyborg_nodes.dm
modular_doppler/modular_species/species_types/android/chassis_kit.dm
tgstation.dme

Adds the chassis assembly kit, a device printable in the exofab that can be configured and deployed into the framework to construct an android body. Robotics finally gets to join its sister department of genetics in the divine act of "creating weird corpses because someone got gibbed".
The kit spawns a torso with no organs, no limbs, and no blood, and is intended to have the rest of its components hand-assembled by the robotics division. The chassis can have its name, gender, flavortext, species description, and antenna design all changed manually before deployment. Alternatively, a cybernetic brain (specifically from androids) can be scanned to use its preferences for the created body.
The scanning part of this puts it in a sort of awkward halfway between being in a completely new body, …

Chassis assembly kit

---

modular_doppler/_HELPERS/preferences.dm
modular_doppler/modular_quirks/traumatized/traumatized.dm
tgstation.dme
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/dopplershift_preferences/traumatized.tsx

Like 3 hours ago Dopamiin was like "I wish there was a quirk that would let you start with a certain brain trauma"
Please yell at me if the Typescript is weird or I put things where they don't belong organization wise
In modular _HELPERS I've initialized a Global List for the options this quirk has.
Dopamiin wanted to play Monophobia
I wanted to play Dumb, and or Aphasia
The Poltergeist or Stalker ones are pretty cool too. 
The list of options is manually selected rather than generated. I've excluded: Any brain trauma that's strictly positive rather than negative, traumas given by other quirks, Split Person, Imaginary Friend, and all Heretic traumas. 
The rest of the Mild and Severe Traumas are included. 
:cl:
add: You can choose a brain trauma for your creacher
/:cl:

Adds Traumatized, a quirk that lets you pick a brain trauma to be stuck with

---

code/controllers/subsystem/job.dm
code/datums/records/manifest.dm
code/modules/jobs/job_types/security_officer.dm
modular_doppler/alt_job_titles/alt_job_title_modifiers.dm
modular_doppler/alt_job_titles/job.dm
tgstation.dme

So this fixes security officer alt titles by... well. It just makes the security officer job re-run alt title setup after assigning a sub-department.
I considered simply moving alt title setup until after security officers handle their thing, but really security officers are the snowflake'd behaviour here and for most other jobs the current place works better. Hence! Just making it so security officers re-run it if need be.
Now, doing *just* that would simply override the subdepartment rank with the given alt title, which feels off.
So we implement a new proc `/datum/id_trim/proc/get_modified_title(base_title)`, which allows a given trim to decide whether we should be applying some flavour of modification to a given alt title.
This allows us to make the departmental security officer trims …

Fix security officer alt titles not working with subdepartment assignments

---

code/modules/jobs/job_types/security_officer.dm

All this does is comment out the line where it gets the algorithmically assigned department, thus having it default to prefs.
By allowing security officers to actually pick which department they get assigned to they may theoretically integrate better with the crew- being a familiar face that's here willingly rather than today's random outside force.
:cl:
balance: [DOPPLER] The security subdepartment preference actually assigns you to that department, instead of using it to algorithmically pair you up.
/:cl:

[NON-MODULAR] Allow security officers to actually pick their department.

---

_maps/map_files/Pubbystation/pubbystation.dmm

one of pubby's weakest points rn, besides maint being kinda weirdly made, is its aesthetics (this is an old map, remember, just recently ported and updated). this is an aesthetic pass on cargo. kind of hard to take screenshots of. no 'actual' changes, just makes stuff look fancier
wowww
woahhhhhh
:cl:
add: decorations to pubby cargo
/:cl:

smol pubbers cargo aesthetic pass

---

modular_doppler/modular_weapons/code/sec_swords/sheath.dm

Simply swaps attack_hand vs attack_hand_secondary for the sec sheathe. And the return values because secondary clicks runtime if you don't play nicely with them.
When I play sec, and I suddenly need to draw a weapon, i click on the sheathe. I go sicko mode and suddenly IM the bad guy
Minor change. Isn't about to solve everyone's issues. But I think we'd (or I'd) benefit from the kneejerk reaction being the less-lethal option
:cl:
qol: swapped the primary and secondary click functions for the sec sheathe
/:cl:

Reverses the mouse actions on the security sheathe

---

modular_doppler/shuttle_gear/code/ore_scoop.dm

Shuttle ore scoops now have a weighted list. This was already supported but for some reason all the ores were set to one. You're now more likely to get more common materials like iron and glass, with more weighting given to titanium because of it's use in shuttle construction.
<details>
<summary>The weighted list in question.</summary>
- Iron: 5
- Glass: 5
- Titanium: 5
- Silver: 3
- Gold: 3
- Plasma: 2
- Uranium: 2
- Diamond: 1
- Bluespace: 1
- Plastic: 1
</details>
This PR also fixes shuttle ore scoops only working once and then breaking forever after flying more than once.
You're much more likely to use iron and glass than diamonds or bluespace. And bugs being fixed is good.
:cl:
balance: Shuttle ore scoops are now weighted in which ores they produce.
fix: Shuttle ore scoops no longer …

Shuttle Ore Scoops now have a weighted list and also work more than once.

---

modular_doppler/colony_fabricator/code/design_datums/rations_printer_designs/seeds.dm

Oat Seeds are replaced with Wheat Seeds.
Tower-caps, tobacco and ambrosia vulgaris are added to the printable list.
Even as much as my celiac ass hates to admit it, wheat is kind of an essential plant, and oats mutate from it anyways.
Tower-caps are downright necessary in a colonization scenario, with quite a few things expecting you to be able to produce wood. Considering this is pretty much the only source of these for a colony aside from random luck with weed rolls, yeah...
Ambrosia vulgaris can be grinded down for drugs, toxin and most importantly, Libital and Aiuri, allowing for a semi-primitive way of producing medicine in a colony. It can also be mutated into the safer Ambrosia Deus, which contains omnizine and no inherent toxin.
Tobacco... Is honestly just here as a fun joke more …

Organic Rations Printer synthesized seeds passover

---

modular_doppler/reagent_forging/code/forge_weapons.dm

reduces the spear's reach from 2 tiles to 1 tile, because it was able to hit across z levels, which is pretty bonkers. in exchange it has a 10% block chance. given that it has among the highest damage of a forge weapon at 23, at the cost of not being stackable with a buckler in this mode, it seemed like a decent balance choice.
2 tile reach is kind of busted as is but being able to hit across z levels with relatively impunity against everyone but another spear wielder is a bit goofy. arguably reach shouldn't hit across zs in the first place but its inherited tg behavior and thus way harder to work around

salt nerfs the spear

---

code/__DEFINES/mobs.dm
code/modules/mob/living/brain/brain_item.dm
code/modules/mob/living/carbon/human/species_types/ethereal.dm
code/modules/power/apc/apc_attack.dm
code/modules/surgery/brain_surgery.dm
code/modules/surgery/organs/internal/heart/heart_ethereal.dm
code/modules/surgery/organs/internal/stomach/stomach_ethereal.dm
code/modules/unit_tests/ethereal_revival.dm

1. Lowers Ethereal hunger rate by 25%
2. Adds some messages to draining from an APC for more user feedback
3. Regenerating Ethereals gain traumas that can be cured with surgery instead of permanent ones.
4. Ethereals are vulnerable to damage after regenerating.
5. Ethereals are immune to shocks entirely, tiders rejoice
6. You no longer take toxins damage from being fully charged. (But still from dangerously overcharged)
7. You heal a little bit of toxins if you're in the perfect charge range.
8. Some extra visual indicators for an Ethereal being dangerously overcharged
I'd like to sit for more than five minutes during psych RP without starving to death mainly. The rest of the perks are from what Juni asked me to port.
:cl:
qol: Ethereal changes more suitable for an HRP environment
/:cl:

[NONMODULAR] When she told me WE should port this she meant YOU should port this (Ethereal changes)

---

modular_doppler/modular_species/species_types/android/android_parts.dm

Androids unintentionally inherited the robot limbs' damage resist, and are currently sitting at a 0.6x mod for **all** brute/burn damage taken. Noticed by someone in discord, everyone seemed to agree that this was probably a bit too good, and it seemed like more an oopsie than anything anyhow.
Despite the name, this isn't really a balancejak thing, although I do think it's ultimately good to not have such crazy damage disparity. Bugs r bad I think.
:cl:
fix: androids now take 0.8x damage instead of the (probably unintended?) 0.6x
/:cl:

Android limbs brute/burn mod bugfix

---

code/modules/mob/living/basic/vermin/cockroach.dm
modular_doppler/modular_mobs/simple_animal/cockroach.dm
modular_doppler/z_lore_rename.dm

more NT lore renaming in modular folder. hauberoaches were squashing and detonating each other. oops! fixed.
TECHNICALLY synthroaches ARE lore so it's an atomized PR
:cl:
add: more NT renames
fix: stopped spikeroaches from getting too excited
/:cl:

more NT lore renaming and also synthroach fix, oops

---

_maps/map_files/Pubbystation/pubbystation.dmm

Woo! Going back into Pubby for another round of dopplerfying.
Here's the highlights:
-Armory: Civilian-Issue lockers have been moved to EVA Storage. An empty Grenade Launcher, an Empty grenade Belt, and three empty bandoliers have been added.
-EVA Storage: The airlock now requires no access on Red Alert. Contents have been changed to help crew assist with threats. The Civilian Issue Gear (six sets of Frontier Armor, Frontier Helmet, and Mini-Egun) are in security-access lockers, requiring a secoff or a command member with appropriate access to open. There is now two biohazard lockers and two radiation lockers.
-Medical: Switched the location of Paramedic Dispatch and Security office. Shrank New Security office for more Treatment Center room. Treatment center now has a crew-facing airlock …

Back at it Again

---

modular_doppler/sec_armor_normalization/sec_armor_normalization.dm
tgstation.dme

did you know that for some insane reason, sec winter coats had 2 seperate armor datums with literally the same values for the chest and hood?
did you know that for some insane reason, detective jackets, sec winter coats, and the sec jacket all had seperate different armor values despite ostensibly doing the same thing?
why?
im changing it now finally. I'm also setting in place some expectations to how you guys should probably armor sec equipment going forward. 
its good for my mental state i don't think it has much effect on the game besides in practice making some slightly better.
cosmetic_sec is for gimmick armor (protects arms or does the cowboy hat thing where it can take a bullet for you)
head_helmet is for helmets and headgears with no gimmicks
suit_armor is the basic armor datum …

Normalizes sec's armor datum insanity going on.

---

modular_doppler/height_scaling/code/preferences.dm

Title.
Conferred with juni and came to the conclusion these scaling options aren't that bad actually.
See https://github.com/Bubberstation/Bubberstation/pull/1264 for how they look. Please tell me if you don't want tallest; it causes artifacting, but we decided to leave it in.
Finally, I can RP being freakishly feet tall.
:cl:
add: Height scaling now includes all possible scaling options
/:cl:

Expands height scaling to SHORTEST and TALLEST and everything inbetween

---

modular_doppler/loadout_categories/categories/clothing.dm

In the merging of an upstream pr for adding a gags blazer and trenchcoat, the brown and noir trenchcoats.
The intent in parity I believe was to replace these two with the gags versions by removing their colour subtypes, but the types in the loadout are actually their own icon states and not the gags types.
This re-adds those.
In the above process it seems the brown trenchcoat also got replaced with the brown suit jacket, due to some repathing shenanigans, this fixes that.
Good to fix, good for people's loadout prefs to not accidentally be swapped with a different thing.
The gags options aren't a suitable replacement for these, as no degree of colour-selection on those maintains the shading of these two items, and you instead get something that looks more like washed out bathrobes.
:cl: …

Restore detective brown/noir trenchcoat/blazer loadout items

---

tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx

A TGUI update changed how `onChange` works. What we *actually* want here, now, is `onBlur`.
This fixes that.
Good when the server doesn't explode.
:cl:
fix: [DOPPLER] Typing in the large text inputs no longer makes the server explode.
/:cl:

Updates our input prefs to use `onBlur` instead

---

tgui/packages/tgui-say/styles/colors.scss

The tguisay window for the IRC quicktype had become pitch black and unreadable.
Seems the colour for this got lost in a parity update.
Less jank
:cl:
fix: [DOPPLER] The shift-y IRC tguisay is no longer pitch black and unreadable, and back to its original colour.
/:cl:

Makes the IRC tguisay thingy not pitch black and unreadable again

---

code/modules/mob/living/carbon/human/_species.dm

As on the tin.
Missed an if statement, causing `replace_body(...)` to get the dna and set the legs regardless of whether or not this species had leg customization set or not.
MY LEGS OH GODS MY LEGS- oh they're okay now :)
:cl:
fix: [DOPPLER] Species without the leg type preference no longer get the leg type preference applied anyway.
/:cl:

Species without the leg type preference no longer get the leg type preference applied anyway

---

code/__DEFINES/mobs.dm

Tin.
`BODY_HAND_LAYER` was set to `23.99`, despite this being below `GLOVES_LAYER` and lower numbers meaning it gets layered higher.
This pr sets it to `24.99` instead, putting it back between `GLOVES_LAYER 24` and `BODYPARTS_HIGH_LAYER 25` (hands).
less jank
:cl:
fix: [DOPPLER] Hand markings no longer layer on top of gloves.
/:cl:

Fixes hand markings layering over gloves

---

code/modules/mob/living/carbon/carbon_context.dm

Tin.
Just another attempt to make players aware some tails can store items.
:cl:
add: Tails with storage and saddlebags with storage now give screen-tips when appropriate
/:cl:

Adds screen-tip for accessable storage items/organs

---

modular_doppler/shuttle_gear/code/wirefix.dm
tgstation.dme

forces all power cables on a shuttle to reset themselves like they were just built again to prevent shuttles from losing power when rotated
there's a lot of bad mouthfeel when your shuttle powernet needs to be rebuilt just because you foolishly rotated your shuttle, players shouldn't have to deal with such things
:cl:
fix: fixes that kinda annoying shuttle powernet bug
/:cl:

fixes that really annoying shuttle powernet bug in a probably really bad way

---

modular_doppler/mining/equipment/trophies_misc.dm

removes the 20% detonation damage penalty on the skillchecker
after you stack all your upgrades, it actually becomes flat-out better to just not have the skillchecker on the weapon, and that's kind of weird. so, just removes the stat penalty
:cl:
balance: skill checker no longer lowers normal detonation damage
/:cl:

BLATANT mining powercreep that WILL unbalance the game and make it unfun for everybody

---

_maps/doppler/cantina/badguyzone.dmm
code/__DEFINES/radio.dm
code/game/machinery/telecomms/broadcasting.dm
modular_doppler/modular_antagonists/cantina/cantina_items.dm
modular_doppler/modular_antagonists/cantina/cantina_roles.dm
modular_doppler/modular_antagonists/cantina/spawners.dm

Simply removes airless tiles, makes the holopad secure, and gives the cantina regulars/bartenders unassigned jobs to their bank accounts so they're technically real. The bank account bit would require an upstream refactor of bank accounts in general to work any better than that, sadly.
This also changes regular syndicate bowman headsets into chameleon headsets, without all the comms channels and flashbang protection immediately.
~~I do want to look into a solution that lets the cantina in general hear station comms so they can coordinate based on such while in the cantina, but that it outside of the scope of this pr.~~
Edit: The syndicate comms ONLY encryption key has been added to their backpacks, making it still spawned with but opt-in. Annoyingly syndicate comms only encryption keys …

Antag Cantina Revision 2: Less comms (for now), mapping fixes, account fixes

---

code/modules/admin/verbs/adminshuttle.dm
modular_doppler/autotransfer/autotransfer.dm
modular_doppler/autotransfer/shuttle.dm
modular_doppler/autotransfer/transfer_vote.dm

Sooooooo in one of the recent rounds the transfer shuttle passed unintentionally, and as an admin attempted to recall it- it just didn't do anything.
Even if you could, it'd still brick the events subsystem!
This just makes the Cancel Shuttle admin verb reset the end of shift changes when you use it, allowing it to actually be recalled and unbricking the events subsystem.
We also rename `autoEnd()` to `call_end_of_shift_shuttle()` to be slightly clearer.
less jank :+1:
:cl:
admin: [DOPPLER] Cancel Shuttle admin verb can actually cancel the end of shift shuttle.
/:cl:

Allows admins to recall the end of shift shuttle

---

modular_doppler/flavortext_and_records/code/physiology.dm

anthropoid was kinda weird yeah; also adds one for genemods because 'genemodder' has no swag.
'anthropoid' was clunky and sounds like some sort of esoteric slur for the great human race, bit we do still need it to be equivalent to 'reptilian' and 'crystalline' incase you wanna do cool stuff with it that isn't just a normal guy.
:cl:
add: 'Anthropoid' is swapped out for 'Hominin,' 'Genemodder' is swapped out for 'Splicer.'
/:cl:

changes some species descnames around

---

code/datums/storage/subtypes/holsters.dm
modular_doppler/modular_weapons/code/ammo/detective_holster.dm
modular_doppler/modular_weapons/code/ammo_stacks/ammo_stack_base.dm
modular_doppler/modular_weapons/code/ammo_stacks/europa_25.dm
modular_doppler/modular_weapons/code/ammo_stacks/gibraltar.dm
modular_doppler/modular_weapons/code/ammo_stacks/naraka_585.dm
modular_doppler/modular_weapons/code/ammo_stacks/nb_34.dm
modular_doppler/modular_weapons/code/ammo_stacks/shotgun_12ga.dm
tgstation.dme

So yeah, assorted fixes to the gun pr in post.
Refactors `attackby(...)` to `item_interaction(...)`, removes the commented out code, and updates its balloon alerts closer to standards. Balloon alerts shouldn't fill in names to avoid being too long, and blocking balloon alerts should have an exclamation point. I feel some of these weren't actually useful to the player, i.e. caliber mismatch should never come up unless the dev also applies a mismatched ammo stack.
Overlays should be done on `update_overlays(...)` instead of cutting and adding them. We also add `KEEP_TOGETHER` such that it renders as one pile, and thus gets an outline. We also use a single var and some math instead of a list for every ammo stack type.
The `can_shatter` element isn't actually perfect for what we want here. …

Assorted ammo fixes

---

modular_doppler/modular_cosmetics/code/hats/doppler_command_hats.dm

The icon states of these items were being set to the base `post_init_icon_state` of the beret, despite these berets having other gags settings nulled out.
To fix this, we null out `post_init_icon_state` like the other gags settings so it doesn't do this.
:cl:
fix: [DOPPLER] Fix slim/command berets being invisible.
/:cl:

Fix slim/command berets being invisible.

---

_maps/map_files/Mining/Iceland.dmm

Replaces the Ahkter variant battery pack SMES units in the mining base with a standard pre-charged SMES unit. Mining base should actually have a power supply at round start again.
To be reverted if/when a fix for round-start battery packs lacking internal cells is merged.

Temp fix for Iceland Mining Base Power

---

code/datums/quirks/negative_quirks/fluoride_stare.dm

extends flouride stare grace period to 15 mins
wild it's like this in basecode honestly let me stop rping every 3 minutes to mechanically give myself eyedrops
:cl:
qol: flouride stare can be used without losing will to live
/:cl:

Update fluoride_stare.dm | lengthen from 3 minutes to 15

---

modular_doppler/modular_medical/reagents/pill_bottles.dm

During one of the parity prs, where pill bottles got refactored, we forgot to add `spawn_count` var to given pill bottles.
This fixes that.
Fixes #682.
:cl:
fix: Synthetic medicine pill bottles no longer spawn empty.
/:cl:

Fixes modular synth medicine pill bottles spawning empty.

---

code/modules/mob/living/carbon/examine.dm
code/modules/mob/living/silicon/ai/examine.dm
code/modules/mob/living/silicon/robot/examine.dm
modular_doppler/temporary_flavor_text/temp_flavor_text.dm

Really just a pile of assorted fixes as on the tin.
We first replace the examine code for temporary flavortexts with a single proc we re-use, and apply what's needed there.
Silicons need some specialcased code, as silicon topics don't carry over the parent topics and borg overlays aren't handled the same way as for other objects or living beings.
Broadly this reduces the amount of non-modular code though, because we lower the silicon temporary flavortext examines to `/mob/living`.
We also allow for pAI/AI cards to handle their silicon's temporary flavortext with a new hook for updating holder appearance, but this is mostly just modular overrides.
It's good when things actually work.
Dead AIs still having their temporary flavortext feels fitting as it sometimes may be related to the core …

Assorted temporary flavortext fixes/improvements.

---

modular_doppler/modular_cosmetics/code/belt/crusaderbelt.dm

So the loadout crusader belt was calling `PopulateContents()` manually, meaning it got called twice and caused both slots to be filled with pouches.
This fixes that!
We also do some minor code cleanup, but not a full refactor cause oauaaoaugh that'd be a mess. Parsnip sabres though.
less jank good :+1:
Parsnip sabres should probably be on the list of swords, given the whole recent thing upstream for parsnip sabre sheaths and whatever.
:cl:
balance: Parsnip sabres can be stored in the crusader belt.
fix: Crusader belts once again have one pouch and one slot for a sword.
code: Crusader belts have been minorly cleaned up code-wise. Please report any issues.
/:cl:

Fix crusader belt not having space for a sword, minor code cleanup

---

code/modules/loadout/categories/glasses.dm
modular_doppler/loadout_categories/categories/glasses.dm

We've reached a quite unwieldy level of items in our loadout, and this is a step forward in seeking to resolve that, applying it to the glasses loadout category first.
The two methods I use for this are:
1. Sorting the loadout into subgroups, for any coherent group larger than 5 items. This makes browsing our loadouts significantly more manageable.
2. Renaming items into a "type (modifiers)" format wherever applicable. This makes it easier to find specific things when searching for them, and also sorts all similar options nicely together.
To do this sanely we however comment out the full list of the base tg glasses category options, and move these to our modular file.
Categorizing makes it easier to browse, the consistent "type (modifiers)" naming makes it easier to search for things.
Odd …

Reorganize the loadout, part 1: Glasses

---

code/modules/cargo/packs/organic.dm
modular_doppler/modular_cargo/doppler_cargo_packs.dm

Using some appropriated code from one of Bubber's cargo expansions, hydroponics can now order plant samples normally exclusive to Indecipheres at a notable premium. Harvesting this shit from Truth wasn't easy!  
You getting these samples is complete rng otherwise, the only other source is the lavaland ruin on the surface of Truth
I ran it earlier, the crate costed like 2000 cr
:cl:
add: After some (very painful) harvesting and cultivation of flora from a certain ruin on Truth, PA has approved some otherwise Indecipheres-exclusive plant samples for order by hydroponics. 
/:cl:

miniports planetary samples to cargo

---

modular_doppler/modular_species/species_types/android/android.dm

Androids have a death_sound now. Identical to cyborgs.
issa good noise and i wanna hear my creatures when they DIE
^^you cant hear it but trust me it sounded epic
:cl:
add: death sound for androids
/:cl:

I have no mouth but I will scream

---

modular_doppler/modular_jobs/command_bodyguard/code/command_bodyguard.dm

Does what it says on the tin: The skillchip no longer spawns in a bodyguard's brain, and instead is moved to the backpack. 
I've heard complaints by a bodyguard main who hates having to remove the chip roundstart. It disables pushing and using ranged weapons, and not everyone is about having to wait for the chip to "cool off" before removing it.
Yea it builds
:cl:
qol: The evil boxing skillchip is no longer installed by default for the command bodyguard
/:cl:

Makes the command bodyguard's skillchip spawn in their backpack

---

modular_doppler/loadout_categories/categories/backpacks.dm

As title.
The civilian variant of the modsuits does not come with EVA pressurization or temperature control like a full space suit. However, it does come with 12 complexity, a storage module, flashlight, and welding protection (on a battery).
Modsuit technology is a known variable in-setting, and more access to the suits would promote interaction with robotics/science as a whole. Being available in the loadout, characters can reflect some of the traits that would come with a personally-owned modsuit, such as being tech savvy, being emotionally/psychologically dependent on wearing a modsuit without being entombed, or enjoying the ability to plug-and-play with the maint modules. (mobile tanning bed, anyone?)
Primary balance concern would be the increased availability of modsuit cores on …

Adds the Civilian Modsuit to the Backpack Loadout Category
